### PR TITLE
Upgrade to version 12.112.3  (12.112.1/12.112.2)

### PR DESCRIPTION
**Pull request by memo-567**
## Changes in this version:

**Note:**

- YunoHost >= 11.0.7 is required
- PostgreSQL 12.x / 13.x is required
- Node.js 16.15.0 or later is required
- Currently the installation fails in the arm64 environment. This will be fixed in the next version.

**Bugfixes:**

Server: Fix GenerateVideoThumbnail failed
Server: Ensure temp directory cleanup
Favicons of federated instances not showing
Admin: The checkbox for blocking an instance works again
Client: Prevent access to user pages when not logged in
Client: Disable some hotkeys (e.g. for creating a post) for not logged in users
Client: Ask users that are not logged in to log in when trying to vote in a poll
Instance mutes also apply in antennas etc.

**Improvements:**
Server: Allow GET method for some endpoints
Server: Auto NSFW detection
Server: Add rate limit to i/notifications
Client: Improve control panel
Client: Show warning in control panel when there is an unresolved abuse report
Client: Add instance-cloud widget
Client: Add rss-ticker widget
Client: Removing entries from a clip
Client: Poll highlights in explore page
Client: Improve deck UI
Client: Word mute also checks content warnings
Client: Allow pages to be reloaded from the menu
Client: Improve emoji picker performance
Client: For notes with specified visibility, show recipients when hovering over visibility symbol. 
Client: Make widgets available again on a tablet
Ability to leave moderation notes to users
Make possible to delete an account by admin
Improve player detection in URL preview
Add Badge Image to Push Notification
Server: Improve performance
Server: Supports IPv6 on Redis transport.
IPv4/IPv6 is used by default. You can tune this behavior via redis.family.
Server: Add possibility to log IP addresses of users
Add additional drive capacity change support

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
**In my test environment:**

Install 12.112.1 ~ ynh1 on YunoHost 11.0.7 (testing) ✅
Upgrade 12.111.1 ~ ynh1 to 12.112.1 ~ ynh1 on YunoHost 11.0.7 (testing) ✅
Upgrade 12.110.1 ~ ynh1 to 12.112.1 ~ ynh1 on YunoHost 11.0.7 (testing) ✅


**In my productive environment:**

Upgrade 12.111.1 ~ ynh1 to 12.112.1 ~ ynh1 on YunoHost 11.0.7 (testing) ✅

**Comment by memo-567** [comment]
CI Bullseye Job #4038 Misskey restarted, due to "Install private" fail.

**Comment by memo-567** [comment]
[68747470733a2f2f63692d617070732d62756c6c736579652e79756e6f686f73742e6f72672f63692f73756d6d6172792f343033382e706e67](https://ci-apps-bullseye.yunohost.org/ci/job/4038)

**Comment by memo-567** [comment]
Update to 12.112.2 came right after 12.112.1

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
**In my productive environment:**

Upgrade 12.112.1 ~ ynh1 to 12.112.2 ~ ynh1 on YunoHost 11.0.7 (testing) ✅

**Review by ericgaspar — APPROVED** [review]

**Comment by memo-567** [comment]
Update to 12.112.3 came right one day after 12.112.2

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
**In my productive environment:**

Upgrade 12.112.2 ~ ynh1 to 12.112.3 ~ ynh1 on YunoHost 11.0.7 (testing) ✅

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
