### PR TITLE
Upgrade to version 12.111.1

### PR DESCRIPTION
**Pull request by memo-567**
## Changes in this version:

**Note:**

- YunoHost >= 11.0.7 is required
- PostgreSQL 12.x / 13.x is required
- Node.js 16.15.0 or later is required

**Bugfixes:**

Some fixes of multiple notification read
Some GenerateVideoThumbnail failed
Client: Fixed an issue where widget information was not saved in the deck
Client: An edit screen appears when I try to open a post in the gallery

## PR Status
- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by memo-567** [comment]
!testme

**Comment by memo-567** [comment]
### Upgrade seems to work with PostgreSQL 13.7  but not with 11.16 !

_(PostgreSQL 12.x / 13.x is preferred by Misskey developers.)_

I know how to upgrade my Debian installation manually and the upgrade runs smooth and successful on test environment, but I don't know how to do this in a YunoHost script.

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by Limezy** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
The upgrade aborts on YunoHost 4.3.6.3 (stable), as desired, with a message, and runs on YunoHost 11.0.7 (testing) without any problems.

Tested on my productive server.

**Comment by ericgaspar** [comment]
Superseded by #102

**Pull request closed without merging**
