### PR TITLE
Update app.src

### PR DESCRIPTION
**Pull request by oufmilo**
## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@oufmilo Thanks for the PRs. 
It is better to do only one PR with all the changes so we can validate with the CI

**Comment by oufmilo** [comment]
Ok sorry I will try for the next time, I'm novice.

**Comment by ericgaspar** [comment]
no problem. you help is very welcome

**Pull request closed without merging**
