### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Tagadda** [comment]
Sounds like it's working
[Test Badge](https://bleu.cant.at/ci/job/24)
[](https://bleu.cant.at/ci/job/24)

**Comment by ericgaspar** [comment]
!testme

**Comment by memo-567** [comment]
If the result looks good, will this automatic upgrade also include `npm run clean`, or is that not necessary anymore?

Google Translation:

> 12.104.0 (2022/02/09)
> Note
> Run `npm run clean` before building.

Source:
https://github.com/misskey-dev/misskey/blob/develop/CHANGELOG.md#:~:text=12.104.0%20(2022/02,%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82

**Pull request merged**
