### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *[Apply last example_ynh](https://github.com/YunoHost-Apps/misskey_ynh/commit/bcc065634b365c80e773ea6f6e8d30a79c682a07)*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by memo-567** [comment]
Thanks for your trust, but I'm really not sure if I'm the right person to review your changes.
I'm just an enthusiast - not an expert.

On the other hand, beginning with version 12.111.1~ynh1 (Misskey 12.111.1) YunoHost >= 11.0.7 is required, as PostgreSQL >= 12.x is mandatory.

So the previous ones seem to be obsolete with Misskey.

**Comment by memo-567** [comment]
One more thought:

Since the content of Misskey is very dynamic, lots of public posts, but also possibly DM and follow-up requests in just a minute, it might be useful during an upgrade to stop the Misskey service first and then start the backup afterwards.
Then start the service after Misskey has been successfully updated, or the backup has been restored as usual.

Unless this is not possible / desired due to the process.

That way, if something went wrong during the upgrade process, no messages will be lost.

**Review by memo-567 — COMMENTED** [review]
Reviewed - to my best knowledge.

**Pull request merged**
