### PR TITLE
Upgrade to version 12.116.1 (12.114.0 / 12.115.0 / 12.116.0)

### PR DESCRIPTION
**Pull request by memo-567**
## Changes in this version:

**Note:**

- YunoHost >= 11.0.7 is required
- PostgreSQL 12.x / 13.x is required
- Node.js 16.15.0 or later is required
- Still not working on arm64 environment. 

**Improvements:**
- Display order can be shuffled with RSS ticker
- Client: Deck profile switching made easy
- Client: UI brush up
- Client: registry editor
- 
**Bugfixes:**
- Client: Fixed an issue where the show button on the page did not work in the deck UI
- Fixed an issue that could cause the client to stop booting
- Error During Migration Run to 12.111.x
- Server: TypeError: Cannot convert undefined or null to object

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
!bullseyetestme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
