### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add multi_instance

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by oufmilo — CHANGES_REQUESTED** [review]
**Shipped version:** 12.82.0~ynh2

**Review by oufmilo — CHANGES_REQUESTED** [review]
"version": "12.82.0~ynh2",

**Review by oufmilo — CHANGES_REQUESTED** [review]
**Version incluse :** 12.82.0~ynh2

**Comment by oufmilo** [comment]
!testme

**Pull request merged**
