### PR TITLE
Upgrade to version 12.117.1 (12.117.0)

### PR DESCRIPTION
**Pull request by memo-567**
## Changes in this version:

**Note:**

- YunoHost >= 11.0.7 is required
- PostgreSQL 12.x / 13.x is required
- Node.js 16.15.0 or later is required
- Still not working on arm64 environment. 

**Improvements**
- Client: UI brush up
- Client: Allow windows to be maximized
- Client: Now clicks a link while holding down the Shift key to open in an in-app window
- Client: When using a deck, you can now force a page transition by holding down the Ctrl key and clicking a link.

**Bugfixes**
- Server: Fixed an issue that could cause file uploads to fail 
- Client: Fixed an issue where the reaction picker would appear behind the in-app window
- Client: Fixed retry to get user information
- Client: Fixed MFM cheat sheet behavior
- Client: Fixed an issue where the "_Receive notifications from instances_" setting could not be changed

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by memo-567** [comment]
@ericgaspar The next update will probably be released shortly. So a merging doesn't make sense yet.

**Comment by memo-567** [comment]
!bullseyetestme

**Comment by AidanTheBandit1** [comment]
Is there any updates on this?

**Pull request merged**
